services:
  app-integration-mercado-pago:
    image: ${DOCKER_USERNAME}/app-integration-mercado-pago:${IMAGE_TAG}
    container_name: app-integration-mercado-pago
    restart: unless-stopped
    env_file:
      - path: .env.app
        required: false
    expose:
      - "8013"
    networks:
      - db-net
      - infra-net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-integration-mp.rule=Host(`pagamento-api.dev2b.tec.br`)"
      - "traefik.http.routers.app-integration-mp.entrypoints=websecure"
      - "traefik.http.routers.app-integration-mp.tls=true"
      - "traefik.http.routers.app-integration-mp.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-integration-mp.loadbalancer.server.port=8013"

networks:
  db-net:
    external: true
    name: db-net
  infra-net:
    external: true
    name: infra-net
  proxy:
    external: true
    name: proxy
