spring.application.name=app-integration-mercado-pago
server.port=${PORT:8014}

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:app_pagamento}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# MercadoPago
mercadopago.access-token=${MP_ACCESS_TOKEN:}
mercadopago.public-key=${MP_PUBLIC_KEY:}
mercadopago.webhook-secret=${MP_WEBHOOK_SECRET:}
mercadopago.notification-url=${MP_NOTIFICATION_URL:https://50c4-170-239-111-197.ngrok-free.app/webhook/mercadopago}
mercadopago.back-url.success=${MP_BACK_URL_SUCCESS:https://50c4-170-239-111-197.ngrok-free.app/webhook/mercadopago}
mercadopago.back-url.failure=${MP_BACK_URL_FAILURE:https://localhost:3001/pagamento/falha}
mercadopago.back-url.pending=${MP_BACK_URL_PENDING:https://localhost:3001/pagamento/pendente}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}

# Logging
logging.level.br.tec.dev2b=DEBUG

